version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: project-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_management
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: